services:

  web:
    build: 
      context: ./app
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.development
    depends_on:
      - db
    networks:
      - hello_django_network

  db:
    image: postgres:17

    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
    env_file:
      - ./.env.production

    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U hello_django"]
        interval: 5s
        timeout: 5s
        retries: 5

    networks:
      - hello_django_network

volumes:
  postgres_data:

networks:
  hello_django_network:
    driver: bridge