services:

  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.development
    depends_on:
      - db

  db:
    image: postgres:17

    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U hello_djangos"]
        interval: 5s
        timeout: 5s
        retries: 5

volumes:
  postgres_data: